name: '[DEVELOPMENT] Deploy'

on:
  push:
    branches:
      - development
  workflow_dispatch: 

permissions:
  contents: write
  packages: write

jobs:
  Development:
    name: Chainwiki-Development
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      KUBECTL_VERSION: 1.23.5
      CLUSTER_NAME: 'swarm-dev'
      NAMESPACE: 'swarm-dev'

    steps:
      - uses: actions/checkout@v3

      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secrets
        id: load-credentials
        uses: 1Password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://CI-CD/AWS_ACCESS_KEY_ID/credential
          AWS_SECRET_KEY: op://CI-CD/AWS_SECRET_KEY/credential
          ENV_FILE: op://CI-CD/env_chainwiki/notes

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
          chmod 700 get_helm.sh
          sudo bash get_helm.sh

      - name: Install kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/${{ env.KUBECTL_VERSION }}/2021-07-05/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv kubectl /usr/bin/

      - name: Configure kubectl
        id: kubeconfig
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      - name: Get .env file from 1Password
        run: |
          echo $ENV_FILE > .env
          sed -i 's/ \?REACT_APP_/\'$'\nREACT_APP_/g' .env

      - uses: docker/setup-buildx-action@v2.7.0

      - name: Login to Github registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/swarmmarkets/chain-wiki:${{ github.sha }}

      - name: Deployment to dev cluster
        run: |
          helm upgrade --install chainwiki ./chainwiki-chart -f ./chainwiki-chart/values-dev.yaml \
          --set=image.repository="ghcr.io/swarmmarkets/chain-wiki:${{ github.sha }}" \
          -n ${{ env.NAMESPACE }}
